### PR TITLE
refactor : cat mod uses profile impl

### PR DESCRIPTION
**Pull request by UsairimIsani**
Apologies for the delay. Please close the previous pull (#15 ) and consider this one.

@rusty-snake

### CODE REVIEW

**Comment by UsairimIsani** [comment]
Hey, Can you check this one too. @rusty-snake .

**Comment by rusty-snake** [comment]
I did a quick overview already. It looks good so far, but I need to test it when I have the time. I noted two things:
- Some context would be nice `error!("Failed to ...|Can not ...|An error occurred while ...: {}", err)`
- We could refactor rm.rs to only call `remove_file` if `path()` returns `Some(_)` with an `if let`.

BTW: I get notified no matter if you add @rusty-snake or not.

**Comment by rusty-snake** [comment]
Sorry, I lost this from tasks. Can you add some info what failed on errors/warnings. The rest is fine.

**Comment by rusty-snake** [comment]
Thanks for this contribution!

**Comment by UsairimIsani** [comment]
My pleasure, was busy and got sick. Strange times. Take Care.

**Pull request merged**
