### PR TITLE
refactor : has module uses profile impl.

### PR DESCRIPTION
**Pull request by UsairimIsani**
Progresses issues #17 

@rusty-snake

### CODE REVIEW

**Review by rusty-snake — CHANGES_REQUESTED** [review]
This currently checks if the file can be read. A simple check whether the file exists, can be done like this.

```rust
let profile = Profile::new(profile_name, ProfileFlags::default()).unwrap(); // We could also exclude LOOKUP_CWD if we want.
if let Some(path) = profile.path() {
...
```

Have you suggestions for the `profile::Profile` docs to make them easier, so other people can understand the concept of how to use `profile::Profile` the best way?

**Comment by UsairimIsani** [comment]
> This currently checks if the file can be read. A simple check whether the file exists, can be done like this.
> 
> ```rust
> let profile = Profile::new(profile_name, ProfileFlags::default()).unwrap(); // We could also exclude LOOKUP_CWD if we want.
> if let Some(path) = profile.path() {
> ...
> ```
> 
> Have you suggestions for the `profile::Profile` docs to make them easier, so other people can understand the concept of how to use `profile::Profile` the best way?

The reason I chose to read the profile was, if  I read it I know that it exists and has a valid path.

image

The suggested Implementation leads to panics if the file doesn't exist.
image

image

**Comment by rusty-snake** [comment]
> The reason I chose to read the profile was, if I read it I know that it exists and has a valid path.

`profile::lookup_profile` which is called by `profile::Profile::new` already checks if a file exists (if called w/o `ASSUME_EXISTENCE`). On your screenshot are only the flags changed, but not the match/if let.

```rust 
let flags = ProfileFlags::default();
match Profile::new(profile_name, flags) {
    Ok(profile) => ...,
    Err(err) => unreachable!("Profile::new always returns Ok(_) if called w/o READ flag ATM"),
}
```

What I suggested:
```rust 
let flags = ProfileFlags::default();
match Profile::new(profile_name, flags).unwrap().path() {
    Some(path) => // found at path,
    None => // not found,
}
```

**Comment by UsairimIsani** [comment]
image

Does this look ok? @rusty-snake

**Comment by rusty-snake** [comment]
The profile thing yes. However IMHO it should use `println!`. `info!` and `error!` are for logging. Imagine `RUST_LOG` is set to error (default in fjp is info, but env_logger has warn as default), a user would get the requested info only if it is "not found". Or we implement a `--log-to-file` command-line argument later.

(https://rust-lang.github.io/rust-clippy/rust-1.46.0/index.html#single_match_else if you want.)

**Review by rusty-snake — APPROVED** [review]

**Comment by rusty-snake** [comment]
Thanks for this contribution!

**Pull request merged**
